const $ = (selector, root = document) => root.querySelector(selector);
const TOKEN = 'central-ti-token';
const KIT = ['Computador', 'Monitor', 'Teclado', 'Mouse', 'Leitor de cartão', 'Fone'];
const modules = {
  demandas: { name: 'Demandas', icon: '✓', fields: [['titulo', 'Demanda', 'Resumo da demanda'], ['tipo', 'Tipo', 'interna,externa'], ['solicitante', 'Solicitante', 'Nome do solicitante'], ['prioridade', 'Prioridade', 'Baixa,Média,Alta,Crítica'], ['status', 'Status', 'DEMAND_STATUS'], ['empresa', 'Empresa (somente externa)', 'OPTIONAL'], ['contato', 'Contato externo (somente externa)', 'OPTIONAL'], ['email', 'E-mail externo (somente externa)', 'OPTIONAL_EMAIL'], ['descricao', 'Descrição da demanda externa', 'OPTIONAL_TEXTAREA']] },
  computadores: { name: 'Computadores', icon: '▣', fields: [['patrimonio', 'Patrimônio', 'Código ou etiqueta'], ['ip', 'IP da máquina', 'Ex.: 192.168.1.25'], ['grupo', 'Grupo', 'COMPUTER_GROUP'], ['responsavel', 'Responsável', 'Nome do usuário'], ['localizacao', 'Localização', 'Setor / sala'], ['status', 'Status', 'Ativo,Em manutenção,Disponível'], ['avaliacao', 'Avaliação', 'Bom,Ruim,Precisa de manutenção,Troca necessária'], ['dataSolicitacao', 'Data da solicitação', 'DATE_OPTIONAL'], ['dataRetirada', 'Data de retirada / entrega', 'DATE_OPTIONAL'], ['dataDevolucao', 'Data de devolução', 'DATE_OPTIONAL']] },
  materiais: { name: 'Materiais', icon: '◫', fields: [['item', 'Item', 'Nome do material'], ['categoria', 'Categoria', 'Ex.: Escritório'], ['quantidade', 'Quantidade', '0'], ['minimo', 'Estoque mínimo', '0']] },
  recepcoes: { name: 'Recepções', icon: '⌂', fields: [['visitante', 'Visitante', 'Nome completo'], ['empresa', 'Empresa', 'Empresa / órgão'], ['destino', 'Destino', 'Pessoa ou setor'], ['data', 'Data', 'dd/mm/aaaa']] },
  equipamentos: { name: 'Equipamentos', icon: '◉', fields: [['patrimonio', 'Patrimônio', 'Código ou etiqueta'], ['equipamento', 'Equipamento', 'Nome do equipamento'], ['modelo', 'Modelo', 'Marca e modelo'], ['responsavel', 'Responsável', 'Nome do usuário'], ['condicao', 'Condição', 'Operacional,Manutenção,Indisponível'], ['avaliacao', 'Avaliação', 'Bom,Ruim,Precisa de manutenção,Troca necessária']] },
  ramais: { name: 'Ramais', icon: '☎', fields: [['ramal', 'Ramal', 'Ex.: 204'], ['setor', 'Setor', 'Ex.: Faturamento'], ['responsavel', 'Responsável', 'Nome do usuário'], ['status', 'Ativação', 'Ativo,Inativo'], ['funcionamento', 'Funcionamento', 'Bom funcionamento,Com falha,Em manutenção']] },
  redes: { name: 'Redes', icon: '⌁', fields: [['nome', 'Nome', 'Nome do ativo'], ['ip', 'IP / Faixa', 'Ex.: 192.168.1.1'], ['localizacao', 'Localização', 'Setor / rack'], ['status', 'Status', 'Online,Offline,Manutenção']] },
  patrimonio: { name: 'Patrimônio', icon: '◇', fields: [['codigo', 'Código', 'Código patrimonial'], ['descricao', 'Descrição', 'Descrição do item'], ['localizacao', 'Localização', 'Setor / sala'], ['situacao', 'Situação', 'Em uso,Disponível,Baixado']] }
};
const state = { token: localStorage.getItem(TOKEN), user: null, page: 'dashboard', records: [], users: [], messages: [], dashboard: null, report: null, statuses: ['Aberta', 'Em andamento', 'Concluída'], computerGroups: ['Geral', 'Faturamento', 'Eletivas', 'Laboratório'], locations: null, query: '', start: '', end: '', networkUrls: [], modal: null, pending: null, loading: false, formDirty: false };
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const formatDate = value => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));
const role = value => ({ admin: 'Administrador', ti: 'Equipe de TI', recepcao: 'Recepção', consulta: 'Consulta' })[value] || value;
const canWrite = resource => state.user?.perfil === 'admin' || (state.user?.perfil === 'ti' && resource !== 'recepcoes');
const canRead = resource => state.user?.perfil === 'admin' || state.user?.perfil === 'consulta' || (state.user?.perfil === 'ti' && resource !== 'recepcoes') || (state.user?.perfil === 'recepcao' && resource === 'recepcoes');
async function api(url, options = {}) {
  const response = await fetch(url, { ...options, headers: { ...(options.body ? { 'content-type': 'application/json' } : {}), ...(state.token ? { authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.');
  return data;
}
function tag(value) { const text = String(value || ''), normalized = text.toLowerCase(); const kind = /(bom|ativo|online|operacional|concluída|disponível)/.test(normalized) ? 'success' : /(ruim|manutenção|média|andamento)/.test(normalized) ? 'warning' : /(troca|crítica|alta|offline|indisponível|baixado)/.test(normalized) ? 'danger' : ''; return `<span class="tag ${kind}">${esc(text)}</span>`; }
function nav(id, label, icon) { return `<button class="${state.page === id ? 'active' : ''}" onclick="go('${id}')"><span class="nav-icon">${icon}</span><span class="label">${label}</span></button>`; }
function sidebar() { const links = Object.entries(modules).filter(([id]) => canRead(id)).map(([id, module]) => nav(id, module.name, module.icon)).join(''); return `<aside class="sidebar"><div class="brand-lockup"><div class="brand-mark">✦</div><span>Central TI</span></div><nav class="nav"><div class="nav-section">PAINEL</div>${nav('dashboard', 'Visão geral', '⌘')}${nav('relatorios', 'Relatórios', '▤')}${canRead('computadores') ? nav('localizacao', 'Localizar máquinas', '⌖') : ''}<div class="nav-section">GESTÃO</div>${links}${state.user.perfil === 'admin' ? `<div class="nav-section">ACESSOS</div>${nav('usuarios', 'Usuários', '♙')}` : ''}<div class="nav-section">COMUNICAÇÃO</div>${nav('email', 'E-mail interno', '✉')}</nav><div class="user-box"><div class="avatar">${esc(state.user.nome.slice(0, 2).toUpperCase())}</div><div><div class="user-name">${esc(state.user.nome)}</div><div class="user-role">${esc(role(state.user.perfil))}</div></div><button class="logout" onclick="logout()">↪</button></div></aside>`; }
function header(title, subtitle) { return `<div class="topbar"><div><div class="eyebrow">${esc(subtitle || 'Central TI')}</div><h1 class="page-title">${esc(title)}</h1></div></div>`; }
function dashboard() { const d = state.dashboard || { notifications: [], activeCount: 0, openDemands: 0, inbox: 0 }; return `${header('Visão geral', `Olá, ${state.user.nome}`)}<section class="metrics">${[['Ativos cadastrados', d.activeCount, '▣'], ['Demandas abertas', d.openDemands, '✓'], ['Alertas técnicos', d.notifications?.length || 0, '⚠'], ['Mensagens não lidas', d.inbox, '✉']].map(item => `<div class="metric"><div class="metric-head"><div class="metric-name">${item[0]}</div><div class="metric-icon">${item[2]}</div></div><div class="metric-number">${item[1]}</div></div>`).join('')}</section><section class="dashboard-grid"><div class="panel"><div class="panel-heading"><div><h3>Notificações técnicas</h3><div class="panel-subtitle">Itens que exigem atenção</div></div></div><div class="demand-list">${(d.notifications || []).map(note => `<div class="demand"><span class="status ${note.avaliacao === 'Troca necessária' ? 'critical' : 'wait'}"></span><div><div class="demand-title">${esc(note.titulo)} · ${tag(note.avaliacao)}</div><div class="demand-meta">${esc(note.detalhe)}</div></div></div>`).join('') || '<div class="empty">Nenhuma notificação técnica.</div>'}</div></div><div class="panel"><div class="panel-heading"><div><h3>Acesso pela rede</h3><div class="panel-subtitle">Compartilhe com sua equipe</div></div></div><div class="network-box">${state.networkUrls.map(url => `<code>${esc(url)}</code>`).join('') || 'Endereço não identificado.'}<p>Os dados são compartilhados entre todos os usuários da Central TI.</p></div></div></section>`; }
function locationPage() { const data = state.locations || { groups: [], records: [] }; const records = data.records.filter(record => Object.values(record).join(' ').toLowerCase().includes(state.query.toLowerCase())); return `${header('Localizar máquinas', 'Busca por IP, patrimônio, grupo ou setor')}<div class="section-toolbar"><input class="search" value="${esc(state.query)}" oninput="setSearch(this.value)" placeholder="Ex.: 192.168.2.25, PC-0048 ou Faturamento"/></div><section class="location-groups">${data.groups.map(item => `<button onclick="setSearch('${esc(item.group)}')"><b>${esc(item.group)}</b><span>${item.total} máquina(s)</span></button>`).join('')}</section><div class="panel table-panel">${records.length ? `<table class="data-table"><thead><tr><th>Patrimônio</th><th>IP</th><th>Grupo</th><th>Localização</th><th>Responsável</th><th>Status</th></tr></thead><tbody>${records.map(record => `<tr><td><b>${esc(record.patrimonio)}</b></td><td><code>${esc(record.ip)}</code></td><td>${tag(record.grupo)}</td><td>${esc(record.localizacao)}</td><td>${esc(record.responsavel)}</td><td>${tag(record.status)}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">Nenhuma máquina encontrada.</div>'}</div>`; }
function demandBoard() { const cards = state.records.filter(record => record.titulo.toLowerCase().includes(state.query.toLowerCase())); return `${header('Demandas', 'Quadro de trabalho')}<div class="section-toolbar"><input class="search" value="${esc(state.query)}" oninput="setSearch(this.value)" placeholder="Pesquisar demanda..."/><div class="toolbar-actions">${canWrite('demandas') ? `<button class="secondary" onclick="openStatusManager()">⚙ Status</button><button class="add-record" onclick="openRecord('demandas')">+ Nova demanda</button>` : ''}</div></div><div class="kanban">${state.statuses.map((status, index) => `<section class="kanban-column" ondragover="event.preventDefault()" ondrop="dropDemand(event,'${esc(status)}')"><header><span class="kanban-dot dot-${index % 4}"></span><b>${esc(status)}</b><small>${cards.filter(card => card.status === status).length}</small></header><div class="kanban-cards">${cards.filter(card => card.status === status).map(card => `<article class="demand-card" draggable="true" ondragstart="dragDemand(event,'${card.id}')"><div class="demand-card-title">${esc(card.titulo)}</div><div class="demand-card-meta">${esc(card.solicitante)}</div><div class="demand-card-bottom">${tag(card.prioridade)}<select onchange="moveDemand('${card.id}',this.value)">${state.statuses.map(option => `<option ${option === card.status ? 'selected' : ''}>${esc(option)}</option>`).join('')}</select></div></article>`).join('') || '<div class="kanban-empty">Arraste uma demanda para cá</div>'}</div></section>`).join('')}</div>`; }
function recordsPage(resource) {
  const module = modules[resource];
  const rows = state.records.filter(record => Object.values(record).join(' ').toLowerCase().includes(state.query.toLowerCase()));
  const cell = (record, [key, , source]) => {
    const value = record[key] || '';
    if (source === 'DATE_OPTIONAL') return value ? esc(value.split('-').reverse().join('/')) : '—';
    return ['status', 'avaliacao', 'condicao', 'situacao'].includes(key) ? tag(value) : esc(value || '—');
  };
  return `${header(module.name, 'Gestão')}<div class="section-toolbar"><input class="search" value="${esc(state.query)}" oninput="setSearch(this.value)" placeholder="Pesquisar por patrimônio, IP, grupo ou responsável..."/><div class="toolbar-actions"><button class="secondary" onclick="exportResource('${resource}')">⇩ Exportar CSV</button>${resource === 'computadores' && canWrite(resource) ? `<button class="secondary" onclick="openGroupManager()">⚙ Grupos</button>` : ''}${canWrite(resource) ? `<button class="add-record" onclick="openRecord('${resource}')">+ Novo cadastro</button>` : ''}</div></div><div class="panel table-panel">${rows.length ? `<table class="data-table"><thead><tr>${module.fields.map(field => `<th>${field[1]}</th>`).join('')}${resource === 'computadores' ? '<th>Checklist</th>' : ''}<th>Ações</th></tr></thead><tbody>${rows.map(record => `<tr>${module.fields.map(field => `<td>${cell(record, field)}</td>`).join('')}${resource === 'computadores' ? `<td>${record.checklist?.length ? `✓ ${record.checklist.length}/${KIT.length}` : '—'}</td>` : ''}<td><button class="link-button" onclick="openRecord('${resource}','${record.id}')">Editar</button>${canWrite(resource) ? ` <button class="danger-link" onclick="deleteRecord('${resource}','${record.id}')">Excluir</button>` : ''}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">Nenhum registro encontrado.</div>'}</div>`;
}
function reportPage() { const report = state.report || { modules: [], alerts: [], lowStock: [], demandStatus: [], total: 0 }; return `${header('Relatórios', 'Visão consolidada')}<div class="report-actions"><label>De<input type="date" value="${esc(state.start)}" onchange="setPeriod(this.value,state.end)"/></label><label>Até<input type="date" value="${esc(state.end)}" onchange="setPeriod(state.start,this.value)"/></label><button class="secondary" onclick="exportReport()">⇩ Exportar CSV</button><button class="add-record" onclick="window.print()">🖨 Imprimir / PDF</button></div><section class="metrics">${[['Total de registros', report.total], ['Alertas técnicos', report.alerts.length], ['Estoque baixo', report.lowStock.length], ['Demandas concluídas', report.demandStatus.find(item => item.status === 'Concluída')?.total || 0]].map(item => `<div class="metric"><div class="metric-name">${item[0]}</div><div class="metric-number">${item[1]}</div></div>`).join('')}</section><div class="report-grid"><section class="panel"><div class="panel-heading"><h3>Cadastros por módulo</h3></div><table class="data-table"><tbody>${report.modules.map(item => `<tr><td>${esc(modules[item.resource]?.name || item.resource)}</td><td><b>${item.total}</b></td></tr>`).join('')}</tbody></table></section><section class="panel"><div class="panel-heading"><h3>Demandas por status</h3></div><table class="data-table"><tbody>${report.demandStatus.map(item => `<tr><td>${tag(item.status)}</td><td><b>${item.total}</b></td></tr>`).join('')}</tbody></table></section><section class="panel"><div class="panel-heading"><h3>Alertas técnicos</h3></div>${report.alerts.length ? `<table class="data-table"><tbody>${report.alerts.map(item => `<tr><td>${esc(item.item)}</td><td>${tag(item.avaliacao)}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">Sem alertas no período.</div>'}</section><section class="panel"><div class="panel-heading"><h3>Estoque baixo</h3></div>${report.lowStock.length ? `<table class="data-table"><tbody>${report.lowStock.map(item => `<tr><td>${esc(item.item)}</td><td>${item.quantidade}/${item.minimo}</td></tr>`).join('')}</tbody></table>` : '<div class="empty">Sem itens abaixo do mínimo.</div>'}</section></div>`; }
function emailPage() { const unread = state.messages.filter(message => message.recipient.id === state.user.id && !message.readAt).length; return `${header('E-mail interno', 'Comunicação entre usuários')}<section class="mail-layout"><aside class="mail-folders"><button class="add-record" style="width:100%;margin-bottom:10px" onclick="compose()">+ Escrever</button><button class="folder active">✉ Caixa de entrada <b style="float:right">${unread}</b></button><div class="mail-note">As mensagens chegam diretamente aos usuários cadastrados.</div></aside><div class="panel">${state.messages.map(message => `<button class="mail-item ${!message.readAt && message.recipient.id === state.user.id ? 'unread' : ''}" onclick="readMessage('${message.id}')"><div><div class="mail-sender">${message.sender.id === state.user.id ? `Para: ${esc(message.recipient.nome)}` : esc(message.sender.nome)}</div><div class="mail-subject">${esc(message.subject)}</div><div class="mail-preview">${esc(message.body)}</div></div><div class="mail-date">${formatDate(message.createdAt)}</div></button>`).join('') || '<div class="empty">Nenhuma mensagem.</div>'}</div></section>`; }
function usersPage() { return `${header('Usuários', 'Acessos e permissões')}<div class="section-toolbar"><button class="secondary" onclick="createBackup()">▣ Gerar backup</button><button class="add-record" onclick="openUser()">+ Novo usuário</button></div><div class="panel table-panel"><table class="data-table"><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Segurança</th></tr></thead><tbody>${state.users.map(user => `<tr><td>${esc(user.nome)}</td><td>${esc(user.email)}</td><td>${tag(role(user.perfil))}</td><td>${user.mustChangePassword ? tag('Troca de senha pendente') : tag('Senha configurada')}</td></tr>`).join('')}</tbody></table></div>`; }
function field([key, label, source], record) {
  const value = record?.[key] || (key === 'tipo' ? 'interna' : '');
  if (source === 'OPTIONAL_TEXTAREA') return `<label class="field">${label}<textarea name="${key}" rows="3" maxlength="3000" placeholder="Obrigatória quando o tipo for externa">${esc(value)}</textarea></label>`;
  if (source === 'OPTIONAL' || source === 'OPTIONAL_EMAIL') return `<label class="field">${label}<input name="${key}" ${source === 'OPTIONAL_EMAIL' ? 'type="email"' : ''} maxlength="250" value="${esc(value)}" placeholder="Obrigatório quando o tipo for externa"/></label>`;
  if (source === 'DATE_OPTIONAL') return `<label class="field">${label}<input type="date" name="${key}" value="${esc(value)}"/></label>`;
  if (key === 'ip') return `<label class="field">${label}<input name="ip" required inputmode="decimal" maxlength="45" value="${esc(value)}" placeholder="Ex.: 192.168.1.25" title="Informe um endereço IPv4 ou IPv6 válido."/></label>`;
  if (key === 'patrimonio') return `<label class="field">${label}<input name="patrimonio" required maxlength="50" pattern="[A-Za-z0-9][A-Za-z0-9._/-]{1,49}" value="${esc(value)}" placeholder="Ex.: PC-0048" oninput="this.value=this.value.toUpperCase()" title="Use letras, números, ponto, hífen, sublinhado ou barra."/></label>`;
  const options = source === 'DEMAND_STATUS' ? state.statuses : source === 'COMPUTER_GROUP' ? state.computerGroups : source.split(',');
  return `<label class="field">${label}${source.includes(',') || source === 'DEMAND_STATUS' || source === 'COMPUTER_GROUP' ? `<select name="${key}" required><option value="">Selecione</option>${options.map(option => `<option ${option === value ? 'selected' : ''}>${esc(option)}</option>`).join('')}</select>` : `<input name="${key}" required value="${esc(value)}" placeholder="${esc(source)}"/>`}</label>`;
}
function modal() { if (!state.modal) return ''; if (state.modal.type === 'record') { const resource = state.modal.resource, record = state.modal.record, module = modules[resource]; return `<div class="modal-backdrop" onclick="closeBack(event)"><form class="modal modal-wide" onsubmit="saveRecord(event,'${resource}','${record?.id || ''}')"><div class="modal-header"><h2>${record ? 'Editar' : 'Novo cadastro'} · ${module.name}</h2><button type="button" class="close" onclick="closeModal()">×</button></div>${resource === 'computadores' ? '<p class="modal-intro">Cadastre o IP para localizar a máquina na rede. As datas são opcionais e registram o ciclo de solicitação, entrega e devolução.</p>' : ''}<div class="two-col">${module.fields.map(item => field(item, record)).join('')}</div>${resource === 'computadores' ? `<fieldset class="checklist"><legend>Checklist do kit entregue</legend><div class="checklist-grid">${KIT.map(item => `<label class="check-item"><input type="checkbox" name="checklist" value="${item}" ${(record?.checklist || []).includes(item) ? 'checked' : ''}/><span>✓</span>${item}</label>`).join('')}</div></fieldset>` : ''}<div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Salvar</button></div></form></div>`; }
  if (state.modal.type === 'computer-groups') return `<div class="modal-backdrop" onclick="closeBack(event)"><form class="modal" onsubmit="saveComputerGroups(event)"><div class="modal-header"><h2>Grupos de computadores</h2><button type="button" class="close" onclick="closeModal()">×</button></div><p class="modal-intro">Cadastre os grupos que organizam as máquinas, como Faturamento, Eletivas e Laboratório. Grupos em uso não podem ser removidos.</p><div id="group-fields">${state.computerGroups.map(group => `<label class="status-editor"><input name="group" value="${esc(group)}" required maxlength="50"/><button type="button" onclick="this.parentElement.remove()">×</button></label>`).join('')}</div><button type="button" class="secondary" onclick="addComputerGroup()">+ Adicionar grupo</button><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Salvar grupos</button></div></form></div>`;
  if (state.modal.type === 'statuses') return `<div class="modal-backdrop" onclick="closeBack(event)"><form class="modal" onsubmit="saveStatuses(event)"><div class="modal-header"><h2>Status das demandas</h2><button type="button" class="close" onclick="closeModal()">×</button></div><p class="modal-intro">Edite as colunas. Status com demandas não podem ser removidos.</p><div id="status-fields">${state.statuses.map(status => `<label class="status-editor"><input name="status" value="${esc(status)}" required maxlength="50"/><button type="button" onclick="this.parentElement.remove()">×</button></label>`).join('')}</div><button type="button" class="secondary" onclick="addStatus()">+ Adicionar status</button><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Salvar status</button></div></form></div>`;
  if (state.modal.type === 'mail') return `<div class="modal-backdrop" onclick="closeBack(event)"><form class="modal" onsubmit="sendMail(event)"><div class="modal-header"><h2>Nova mensagem interna</h2><button type="button" class="close" onclick="closeModal()">×</button></div><label class="field">Para<select name="recipientId" required><option value="">Selecione</option>${state.users.filter(user => user.id !== state.user.id).map(user => `<option value="${user.id}">${esc(user.nome)} · ${esc(user.email)}</option>`).join('')}</select></label><label class="field">Assunto<input name="subject" required maxlength="160"/></label><label class="field">Mensagem<textarea name="body" required rows="6" maxlength="5000"></textarea></label><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Enviar</button></div></form></div>`;
  return `<div class="modal-backdrop" onclick="closeBack(event)"><form class="modal" onsubmit="saveUser(event)"><div class="modal-header"><h2>Novo usuário</h2><button type="button" class="close" onclick="closeModal()">×</button></div><label class="field">Nome<input name="nome" required/></label><label class="field">E-mail<input name="email" type="email" required/></label><label class="field">Perfil<select name="perfil"><option value="consulta">Consulta</option><option value="ti">Equipe de TI</option><option value="recepcao">Recepção</option><option value="admin">Administrador</option></select></label><label class="field">Senha inicial<input name="senha" type="password" required minlength="8"/></label><div class="modal-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Criar usuário</button></div></form></div>`; }
function loginPage() { if (state.pending) return `<div class="login-page"><section class="login-brand"><div class="brand-lockup"><div class="brand-mark">✦</div><span>Central TI</span></div></section><section class="login-panel"><form class="login-card" onsubmit="verifyCode(event)"><h2>Confirme seu acesso</h2><p>Enviamos um código de seis dígitos para <b>${esc(state.pending.email)}</b>.</p><label class="field">Código<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autofocus/></label><button class="primary">Validar e entrar</button><button type="button" class="login-back" onclick="cancelCode()">Voltar</button></form></section></div>`; return `<div class="login-page"><section class="login-brand"><div class="brand-lockup"><div class="brand-mark">✦</div><span>Central TI</span></div><div class="login-copy"><h1>Toda a sua operação de TI em um só lugar.</h1><p>Dados compartilhados, controle de acesso e comunicação interna.</p></div></section><section class="login-panel"><form class="login-card" onsubmit="authenticate(event)"><h2>Boas-vindas</h2><p>Entre com suas credenciais.</p><label class="field">E-mail<input name="email" type="email" required value="admin@centralti.local"/></label><label class="field">Senha<input name="password" type="password" required value="123456"/></label><button class="primary">Entrar na plataforma</button></form></section></div>`; }
function passwordPage() { return `<div class="login-page"><section class="login-brand"><div class="brand-lockup"><div class="brand-mark">✦</div><span>Central TI</span></div><div class="login-copy"><h1>Proteja seu acesso.</h1><p>Antes de usar o sistema, defina uma senha pessoal e segura.</p></div></section><section class="login-panel"><form class="login-card" onsubmit="changeOwnPassword(event)"><h2>Troca obrigatória de senha</h2><p>Use 12+ caracteres, maiúscula, minúscula, número e símbolo.</p><label class="field">Senha atual<input name="currentPassword" type="password" required autofocus/></label><label class="field">Nova senha<input name="newPassword" type="password" required minlength="12"/></label><button class="primary">Salvar senha e entrar</button></form></section></div>`; }
function render() { if (!state.token || !state.user) { $('#app').innerHTML = loginPage(); return; } if (state.user.mustChangePassword) { $('#app').innerHTML = passwordPage(); return; } const page = state.page === 'dashboard' ? dashboard() : state.page === 'demandas' ? demandBoard() : state.page === 'relatorios' ? reportPage() : state.page === 'email' ? emailPage() : state.page === 'usuarios' ? usersPage() : state.page === 'localizacao' ? locationPage() : recordsPage(state.page); $('#app').innerHTML = `<div class="shell">${sidebar()}<main class="content">${state.loading ? '<div class="loading">Atualizando dados…</div>' : page}</main></div>${modal()}`; }
async function load() { state.loading = true; render(); try { if (state.page === 'dashboard') state.dashboard = await api('/api/dashboard'); else if (state.page === 'demandas') { const [records, statuses] = await Promise.all([api('/api/resources/demandas'), api('/api/demand-statuses')]); state.records = records.records; state.statuses = statuses.statuses; } else if (state.page === 'relatorios') { const params = new URLSearchParams(); if (state.start) params.set('start', state.start); if (state.end) params.set('end', state.end); state.report = await api(`/api/reports?${params}`); } else if (state.page === 'email') { const [mail, users] = await Promise.all([api('/api/messages'), api('/api/users')]); state.messages = mail.messages; state.users = users.users; } else if (state.page === 'usuarios') state.users = (await api('/api/users')).users; else state.records = (await api(`/api/resources/${state.page}`)).records; } catch (error) { toast(error.message); } finally { state.loading = false; render(); } }
async function go(page) { state.page = page; state.query = ''; state.modal = null; if (page === 'localizacao') { state.loading = true; render(); try { state.locations = await api('/api/locations/computadores'); } catch (error) { toast(error.message); } finally { state.loading = false; render(); } return; } load(); }
function setSearch(value) { state.query = value; render(); $('.search')?.focus(); }
function setPeriod(start, end) { state.start = start; state.end = end; load(); }
function openRecord(resource, id = '') {
  state.formDirty = false;
  state.modal = { type: 'record', resource, record: id ? state.records.find(record => record.id === id) : null };
  render();
  addObservationField();
  if (resource === 'computadores') api('/api/computer-groups').then(result => { if (state.modal?.type === 'record' && state.modal.resource === 'computadores' && !state.formDirty) { state.computerGroups = result.groups; render(); addObservationField(); } }).catch(error => toast(error.message));
}
function addObservationField() { const form = document.querySelector('.modal form'); if (!form || form.querySelector('[name="observacoes"]')) return; const field = document.createElement('label'); field.className = 'field observations-field'; field.innerHTML = 'Observações<textarea name="observacoes" rows="5" maxlength="5000" placeholder="Registre informações, atualizações e próximos passos."></textarea>'; field.querySelector('textarea').value = state.modal?.record?.observacoes || ''; const anchor = form.querySelector('.checklist') || form.querySelector('.modal-actions'); form.insertBefore(field, anchor); }
function openStatusManager() { state.modal = { type: 'statuses' }; render(); }
async function openGroupManager() { try { state.computerGroups = (await api('/api/computer-groups')).groups; state.modal = { type: 'computer-groups' }; render(); } catch (error) { toast(error.message); } }
function addStatus() { const row = document.createElement('label'); row.className = 'status-editor'; row.innerHTML = '<input name="status" required maxlength="50" placeholder="Novo status"/><button type="button" onclick="this.parentElement.remove()">×</button>'; $('#status-fields').append(row); }
function addComputerGroup() { const row = document.createElement('label'); row.className = 'status-editor'; row.innerHTML = '<input name="group" required maxlength="50" placeholder="Novo grupo"/><button type="button" onclick="this.parentElement.remove()">×</button>'; $('#group-fields').append(row); }
function openUser() { state.modal = { type: 'user' }; render(); }
async function compose() { if (!state.users.length) state.users = (await api('/api/users')).users; state.modal = { type: 'mail' }; render(); }
function closeModal(force = false) { if (!force && state.formDirty && !confirm('Há dados não salvos. Deseja fechar mesmo assim?')) return; state.modal = null; state.formDirty = false; render(); }
function closeBack(event) { if (event.target === event.currentTarget) closeModal(); }
async function saveRecord(event, resource, id) { event.preventDefault(); const form = new FormData(event.target), data = Object.fromEntries(form); if (resource === 'computadores') data.checklist = form.getAll('checklist'); try { await api(`/api/resources/${resource}${id ? `/${id}` : ''}`, { method: id ? 'PUT' : 'POST', body: JSON.stringify(data) }); closeModal(true); await load(); toast('Cadastro salvo.'); } catch (error) { toast(error.message); } }
async function deleteRecord(resource, id) { if (!confirm('Excluir este registro?')) return; try { await api(`/api/resources/${resource}/${id}`, { method: 'DELETE' }); await load(); toast('Registro excluído.'); } catch (error) { toast(error.message); } }
function dragDemand(event, id) { event.dataTransfer.setData('demandId', id); }
async function dropDemand(event, status) { event.preventDefault(); await moveDemand(event.dataTransfer.getData('demandId'), status); }
async function moveDemand(id, status) { const demand = state.records.find(record => record.id === id); if (!demand || demand.status === status) return; try { await api(`/api/resources/demandas/${id}`, { method: 'PUT', body: JSON.stringify({ ...demand, status }) }); await load(); toast(`Demanda movida para ${status}.`); } catch (error) { toast(error.message); } }
async function saveStatuses(event) { event.preventDefault(); const statuses = new FormData(event.target).getAll('status').map(value => value.trim()).filter(Boolean); try { const result = await api('/api/demand-statuses', { method: 'PUT', body: JSON.stringify({ statuses }) }); state.statuses = result.statuses; closeModal(true); await load(); toast('Status atualizados.'); } catch (error) { toast(error.message); } }
async function saveComputerGroups(event) { event.preventDefault(); const groups = new FormData(event.target).getAll('group').map(value => value.trim()).filter(Boolean); try { const result = await api('/api/computer-groups', { method: 'PUT', body: JSON.stringify({ groups }) }); state.computerGroups = result.groups; closeModal(true); toast('Grupos atualizados.'); } catch (error) { toast(error.message); } }
async function sendMail(event) { event.preventDefault(); try { await api('/api/messages', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); closeModal(true); await load(); toast('Mensagem enviada.'); } catch (error) { toast(error.message); } }
async function readMessage(id) { const message = state.messages.find(item => item.id === id); if (message?.recipient.id === state.user.id && !message.readAt) { await api(`/api/messages/${id}/read`, { method: 'PUT' }); load(); } }
async function saveUser(event) { event.preventDefault(); try { await api('/api/users', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); closeModal(true); await load(); toast('Usuário criado.'); } catch (error) { toast(error.message); } }
async function changeOwnPassword(event) { event.preventDefault(); try { await api('/api/auth/change-password', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); state.user.mustChangePassword = false; toast('Senha atualizada com sucesso.'); load(); } catch (error) { toast(error.message); } }
async function createBackup() { try { const result = await api('/api/backups', { method: 'POST' }); toast(result.message || 'Backup criado.'); } catch (error) { toast(error.message); } }
async function openHistory(resource, id) { try { const result = await api(`/api/resources/${resource}/${id}/history`); const lines = result.logs.map(log => `${formatDate(log.createdAt)} — ${log.userName || 'Usuário'}: ${log.action}`).join('\n'); alert(lines || 'Ainda não há movimentações registradas.'); } catch (error) { toast(error.message); } }
async function download(url, name) { const response = await fetch(url, { headers: { authorization: `Bearer ${state.token}` } }); if (!response.ok) return toast('Falha na exportação.'); const link = document.createElement('a'); link.href = URL.createObjectURL(await response.blob()); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
function exportResource(resource) { download(`/api/resources/${resource}/export`, `central-ti-${resource}.csv`); }
function exportReport() { const query = new URLSearchParams(); if (state.start) query.set('start', state.start); if (state.end) query.set('end', state.end); download(`/api/reports/export?${query}`, 'relatorio-central-ti.csv'); }
async function finishLogin(result) { state.token = result.token; state.user = result.user; state.pending = null; localStorage.setItem(TOKEN, state.token); const me = await api('/api/me'); state.networkUrls = me.networkUrls || []; load(); }
async function authenticate(event) { event.preventDefault(); try { const result = await api('/api/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); if (result.requiresVerification) { state.pending = result; render(); return; } await finishLogin(result); } catch (error) { toast(error.message); } }
async function verifyCode(event) { event.preventDefault(); try { const result = await api('/api/auth/verify-email', { method: 'POST', body: JSON.stringify({ verificationToken: state.pending.verificationToken, code: new FormData(event.target).get('code') }) }); await finishLogin(result); } catch (error) { toast(error.message); } }
function cancelCode() { state.pending = null; render(); }
async function logout() { try { await api('/api/auth/logout', { method: 'POST' }); } catch {} state.token = null; state.user = null; state.pending = null; localStorage.removeItem(TOKEN); render(); }
function toast(message) { $('.toast')?.remove(); const toastElement = document.createElement('div'); toastElement.className = 'toast'; toastElement.textContent = message; document.body.append(toastElement); setTimeout(() => toastElement.remove(), 3500); }
async function boot() { if (!state.token) return render(); try { const me = await api('/api/me'); state.user = me.user; state.networkUrls = me.networkUrls || []; load(); } catch { state.token = null; localStorage.removeItem(TOKEN); render(); } }
document.addEventListener('input', event => { if (event.target.closest('.modal form')) state.formDirty = true; });
document.addEventListener('change', event => { if (event.target.closest('.modal form')) state.formDirty = true; });
document.addEventListener('dblclick', event => { const card = event.target.closest('.demand-card'); if (!card || event.target.closest('select')) return; const match = card.getAttribute('ondragstart')?.match(/'([^']+)'/); if (match) openRecord('demandas', match[1]); });
setInterval(() => { if (state.token && state.user && !state.modal && !state.formDirty && !state.loading && state.page !== 'localizacao') load(); }, 15000);
boot();
