function pgDate(value) {
  return value instanceof Date ? value.toISOString() : value || null;
}

function normalizePgDates(row) {
  if (!row) return row;
  const value = { ...row };
  for (const key of ['createdAt', 'updatedAt', 'readAt', 'senderDeletedAt', 'recipientDeletedAt', 'senderArchivedAt', 'recipientArchivedAt', 'dataNascimento']) {
    if (key in value) value[key] = pgDate(value[key]);
  }
  return value;
}

function pgRecord(row) {
  return { id: row.id, ...row.data, createdAt: pgDate(row.created_at), updatedAt: pgDate(row.updated_at), createdBy: row.created_by, updatedBy: row.updated_by };
}

function createPostgresStore({ pool, now, passwordHash }) {
  return {
    async users() { return (await pool.query('SELECT id,nome,email,login,setor,cpf_hash AS "cpfHash",cpf_last4 AS "cpfLast4",data_nascimento AS "dataNascimento",perfil,active,activation_status AS "activationStatus",permissions,salt,hash,must_change_password AS "mustChangePassword",created_at AS "createdAt",updated_at AS "updatedAt" FROM users ORDER BY nome')).rows.map(normalizePgDates); },
    async findUserByEmail(email) { return normalizePgDates((await pool.query('SELECT id,nome,email,login,setor,cpf_hash AS "cpfHash",cpf_last4 AS "cpfLast4",data_nascimento AS "dataNascimento",perfil,active,activation_status AS "activationStatus",permissions,salt,hash,must_change_password AS "mustChangePassword",created_at AS "createdAt",updated_at AS "updatedAt" FROM users WHERE lower(email) = lower($1)', [email])).rows[0]); },
    async findUserByLogin(login) { return normalizePgDates((await pool.query('SELECT id,nome,email,login,setor,cpf_hash AS "cpfHash",cpf_last4 AS "cpfLast4",data_nascimento AS "dataNascimento",perfil,active,activation_status AS "activationStatus",permissions,salt,hash,must_change_password AS "mustChangePassword",created_at AS "createdAt",updated_at AS "updatedAt" FROM users WHERE lower(email) = lower($1) OR lower(login) = lower($1)', [login])).rows[0]); },
    async findUser(idValue) { return normalizePgDates((await pool.query('SELECT id,nome,email,login,setor,cpf_hash AS "cpfHash",cpf_last4 AS "cpfLast4",data_nascimento AS "dataNascimento",perfil,active,activation_status AS "activationStatus",permissions,salt,hash,must_change_password AS "mustChangePassword",created_at AS "createdAt",updated_at AS "updatedAt" FROM users WHERE id = $1', [idValue])).rows[0]); },
    async createUser(user) { await pool.query('INSERT INTO users (id,nome,email,login,setor,cpf_hash,cpf_last4,data_nascimento,perfil,active,activation_status,permissions,salt,hash,must_change_password,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)', [user.id, user.nome, user.email || null, user.login || null, user.setor || '', user.cpfHash || null, user.cpfLast4 || '', user.dataNascimento || null, user.perfil, user.active !== false, user.activationStatus || 'ativo', JSON.stringify(user.permissions || {}), user.salt, user.hash, Boolean(user.mustChangePassword), user.createdAt, user.updatedAt || user.createdAt]); return user; },
    async updateUser(userId, fields) { const columns = { nome: 'nome', email: 'email', login: 'login', setor: 'setor', cpfHash: 'cpf_hash', cpfLast4: 'cpf_last4', dataNascimento: 'data_nascimento', perfil: 'perfil', active: 'active', activationStatus: 'activation_status', permissions: 'permissions', salt: 'salt', hash: 'hash', mustChangePassword: 'must_change_password' }; const entries = Object.entries(fields).filter(([key]) => key in columns); if (!entries.length) return this.findUser(userId); const values = entries.map(([key, value]) => key === 'permissions' ? JSON.stringify(value || {}) : value ?? null); const assignments = entries.map(([key], index) => `${columns[key]}=$${index + 2}`).join(', '); const result = await pool.query(`UPDATE users SET ${assignments}, updated_at=NOW() WHERE id=$1 RETURNING id,nome,email,login,setor,cpf_hash AS "cpfHash",cpf_last4 AS "cpfLast4",data_nascimento AS "dataNascimento",perfil,active,activation_status AS "activationStatus",permissions,salt,hash,must_change_password AS "mustChangePassword",created_at AS "createdAt",updated_at AS "updatedAt"`, [userId, ...values]); return normalizePgDates(result.rows[0]); },
    async renameUser(userId, nome) { return this.updateUser(userId, { nome }); },
    async setUserActive(userId, active) { return this.updateUser(userId, { active }); },
    async setUserPermissions(userId, permissions) { return this.updateUser(userId, { permissions }); },
    async updatePassword(userId, password, mustChangePassword = false) { const values = passwordHash(password); return this.updateUser(userId, { ...values, mustChangePassword }); },
    async records(resource) { return (await pool.query('SELECT id,data,created_at,updated_at,created_by,updated_by FROM records WHERE resource=$1 ORDER BY updated_at DESC', [resource])).rows.map(pgRecord); },
    async record(resource, recordId) { const row = (await pool.query('SELECT id,data,created_at,updated_at,created_by,updated_by FROM records WHERE resource=$1 AND id=$2', [resource, recordId])).rows[0]; return row && pgRecord(row); },
    async createRecord(resource, record) { await pool.query('INSERT INTO records (id,resource,data,created_at,updated_at,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7)', [record.id, resource, record, record.createdAt, record.updatedAt, record.createdBy, record.updatedBy]); return record; },
    async updateRecord(resource, recordId, fields, userId) { const previous = await this.record(resource, recordId); if (!previous) return null; const updated = { ...previous, ...fields, updatedAt: now(), updatedBy: userId }; await pool.query('UPDATE records SET data=$3,updated_at=$4,updated_by=$5 WHERE resource=$1 AND id=$2', [resource, recordId, updated, updated.updatedAt, userId]); return updated; },
    async deleteRecord(resource, recordId) { const previous = await this.record(resource, recordId); if (!previous) return null; await pool.query('DELETE FROM records WHERE resource=$1 AND id=$2', [resource, recordId]); return previous; },
    async messagesFor(userId) { return (await pool.query('SELECT id,sender_id AS "senderId",recipient_id AS "recipientId",thread_id AS "threadId",reply_to_id AS "replyToId",subject,body,attachment_name AS "attachmentName",attachment_mime AS "attachmentMime",created_at AS "createdAt",read_at AS "readAt",sender_deleted_at AS "senderDeletedAt",recipient_deleted_at AS "recipientDeletedAt",sender_archived_at AS "senderArchivedAt",recipient_archived_at AS "recipientArchivedAt" FROM messages WHERE recipient_id=$1 OR sender_id=$1 ORDER BY created_at DESC', [userId])).rows.map(normalizePgDates); },
    async createMessage(message) { await pool.query('INSERT INTO messages (id,sender_id,recipient_id,thread_id,reply_to_id,subject,body,attachment_name,attachment_mime,attachment_data,created_at,read_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)', [message.id, message.senderId, message.recipientId, message.threadId || null, message.replyToId || null, message.subject, message.body, message.attachmentName || null, message.attachmentMime || null, message.attachmentData ? Buffer.from(message.attachmentData, 'base64') : null, message.createdAt, message.readAt]); return message; },
    async messageFor(messageId, userId) { return normalizePgDates((await pool.query('SELECT id,sender_id AS "senderId",recipient_id AS "recipientId",attachment_name AS "attachmentName",attachment_mime AS "attachmentMime",attachment_data AS "attachmentData" FROM messages WHERE id=$1 AND (sender_id=$2 OR recipient_id=$2)', [messageId, userId])).rows[0]); },
    async attachmentUsageFor(userId) { const messages = (await pool.query('SELECT COUNT(*)::int AS count,COALESCE(SUM(octet_length(attachment_data)),0)::bigint AS bytes FROM messages WHERE sender_id=$1 AND attachment_data IS NOT NULL', [userId])).rows[0]; const demands = (await pool.query("SELECT COUNT(*)::int AS count,COALESCE(SUM(octet_length(decode(attachment_data,'base64'))),0)::bigint AS bytes FROM (SELECT data->'anexoPrint'->>'data' AS attachment_data FROM records WHERE resource='demandas' AND data ? 'anexoPrint' AND (data->'anexoPrint'->>'ownerId'=$1 OR (data->'anexoPrint'->>'ownerId' IS NULL AND created_by=$1::uuid)) UNION ALL SELECT interaction.value->'anexoPrint'->>'data' AS attachment_data FROM records CROSS JOIN LATERAL jsonb_array_elements(COALESCE(data->'interacoes', '[]'::jsonb)) AS interaction(value) WHERE resource='demandas' AND interaction.value ? 'anexoPrint' AND (interaction.value->'anexoPrint'->>'ownerId'=$1 OR (interaction.value->'anexoPrint'->>'ownerId' IS NULL AND interaction.value->>'autorId'=$1))) AS attachments WHERE attachment_data IS NOT NULL", [userId])).rows[0]; return { count: Number(messages.count) + Number(demands.count), bytes: Number(messages.bytes) + Number(demands.bytes) }; },
    async markMessageRead(messageId, userId) { return (await pool.query('UPDATE messages SET read_at=NOW() WHERE id=$1 AND recipient_id=$2 RETURNING id', [messageId, userId])).rows[0]; },
    async deleteMessageFor(messageId, userId) { return (await pool.query('UPDATE messages SET recipient_deleted_at=CASE WHEN recipient_id=$2 THEN NOW() ELSE recipient_deleted_at END, sender_deleted_at=CASE WHEN sender_id=$2 THEN NOW() ELSE sender_deleted_at END WHERE id=$1 AND (recipient_id=$2 OR sender_id=$2) RETURNING id', [messageId, userId])).rows[0]; },
    async archiveMessageFor(messageId, userId) { return (await pool.query('UPDATE messages SET recipient_archived_at=CASE WHEN recipient_id=$2 THEN NOW() ELSE recipient_archived_at END, sender_archived_at=CASE WHEN sender_id=$2 THEN NOW() ELSE sender_archived_at END WHERE id=$1 AND (recipient_id=$2 OR sender_id=$2) RETURNING id', [messageId, userId])).rows[0]; },
    async restoreMessageFor(messageId, userId) { return (await pool.query('UPDATE messages SET recipient_archived_at=CASE WHEN recipient_id=$2 THEN NULL ELSE recipient_archived_at END, sender_archived_at=CASE WHEN sender_id=$2 THEN NULL ELSE sender_archived_at END WHERE id=$1 AND (recipient_id=$2 OR sender_id=$2) RETURNING id', [messageId, userId])).rows[0]; },
    async announcements() { return (await pool.query('SELECT id,title,body,author_id AS "authorId",author_name AS "authorName",created_at AS "createdAt" FROM announcements ORDER BY created_at DESC')).rows.map(normalizePgDates); },
    async createAnnouncement(announcement) { await pool.query('INSERT INTO announcements (id,title,body,author_id,author_name,created_at) VALUES ($1,$2,$3,$4,$5,$6)', [announcement.id, announcement.title, announcement.body, announcement.authorId, announcement.authorName, announcement.createdAt]); return announcement; },
    async deleteAnnouncement(announcementId) { const result = await pool.query('DELETE FROM announcements WHERE id=$1 RETURNING id,title,body,author_id AS "authorId",author_name AS "authorName",created_at AS "createdAt"', [announcementId]); return normalizePgDates(result.rows[0]); },
    async audit(entry) { await pool.query('INSERT INTO audit_logs (id,user_id,action,resource,record_id,details,created_at) VALUES ($1,$2,$3,$4,$5,$6,$7)', [entry.id, entry.userId, entry.action, entry.resource, entry.recordId, entry.details, entry.createdAt]); },
    async audits(resource, recordId) { const query = `SELECT a.id,a.action,a.resource,a.record_id AS "recordId",a.details,a.created_at AS "createdAt",u.nome AS "userName" FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE ($1::text IS NULL OR a.resource=$1) AND ($2::uuid IS NULL OR a.record_id=$2) ORDER BY a.created_at DESC LIMIT 100`; return (await pool.query(query, [resource || null, recordId || null])).rows.map(normalizePgDates); },
    async backupNow() { return null; },
    async demandStatuses() { const row = (await pool.query("SELECT value FROM app_settings WHERE key='demand_statuses'")).rows[0]; return row?.value || ['Aberta', 'Em andamento', 'Concluída']; },
    async setDemandStatuses(statuses) { await pool.query("INSERT INTO app_settings (key,value) VALUES ('demand_statuses',$1) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value", [JSON.stringify(statuses)]); return statuses; },
    async computerGroups() { const row = (await pool.query("SELECT value FROM app_settings WHERE key='computer_groups'")).rows[0]; return row?.value || ['Geral', 'Faturamento', 'Eletivas', 'Laboratório']; },
    async setComputerGroups(groups) { await pool.query("INSERT INTO app_settings (key,value) VALUES ('computer_groups',$1) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value", [JSON.stringify(groups)]); return groups; }
  };
}

module.exports = { createPostgresStore };
